package day01vairables.day40CodeUsingJava;

/*
Explanation -
An exception of type Exception is thrown. However we have handled only exception of type

FileNotFoundException. So a compiler error is shown on line 12
 */
public class Exception01 {
}

//class Test {
//    private static void testData() throws Exception {
//        try {
//            System.out.println("TheCertificationGuide");
//            throw new FileNotFoundException();
//        } catch (Exception ex) {
//            ex = null; // Line 11
//            throw ex; // Line 12
//        }
//
//    }
//
//    public static void main(String[] args) throws Exception {
//        try {
//            testData(); // Line 18
//        } catch (FileNotFoundException e) {
//            System.out.println("Caught Exception");
//        }
//    }
//}